### ISSUE TITLE
Some items are not transported to furnaces via Pipe

### ISSUE THREAD

**Issue by LordRazen** [EngineHub/CraftBook#1175]
- Clean Stone -> Smooth Stone
- Quarz Block -> Smooth Quarz
- Sandstone -> Smooth Sandstone
- Red Sandstone -> Smooth Red Sandstone

Upper Items are not transported to furnaces via pipe. I guess they're missing in the receipe list for pipes or so... ^^

**Comment by blek-id** [comment]
To add, most itemms from 1.13.2 upwards can't be filtered through the pipes as well (like phantom membrane).
New item that is an inventory container (such as blast furnace), won't be detected by pipes too

**Comment by me4502** [comment]
What do you mean as filtered through the pipes?

**Comment by me4502** [comment]
Blast furnaces are definitely supported, they just have the same issues as mentioned in the main issue post

**Comment by me4502** [comment]
> Quarz Block -> Smooth Quarz
> Sandstone -> Smooth Sandstone
> Red Sandstone -> Smooth Red Sandstone

Fixed these 3, the other issues I cannot reproduce.
