### ISSUE TITLE
Minecart duplication bug

### ISSUE THREAD

**Issue by korhox** [EngineHub/CraftBook#1178]
Hello!

Players on my server have found a duplication bug. It allows players to duplicate minecarts. You don't even need to have a minecart to get unlimited minecarts for free.

**Steps to reproduce:**
1. Enable MinecartTemporaryCart from config and give permission to use it
2. Right click on a rail (you don't need a minecart since you'll get minecart)
3. Shoot an arrow in to the minecart and it will be destroyed and drops minecart item

It may be possible to destroy the minecart with other ways as well.

**Comment by me4502** [comment]
Try the next dev build.

**Comment by korhox** [comment]
The latest build on builds.enginehub.org (https://builds.enginehub.org/job/craftbook?branch=3.x) has failed and there are no artifacts to download.

Where it should be?

**Comment by me4502** [comment]
Looks like the ProtocolLib Maven Repo is down. It'll have to wait for them to fix their repo.

**Comment by me4502** [comment]
A newer build is out that actually builds
