### ISSUE TITLE
Pipe and filter signs are case sensitive. 

### ISSUE THREAD

**Issue by krusic22** [EngineHub/CraftBook#1181]
Using Paper 1.15.2 with CraftBook 3.10.2-SNAPSHOT;4569-b53bc8b

When placing signs on pistons the text should be case-insensitive,
but writing anything but all lower case will cancel the sign.
The sign will also be canceled if the player is not holding shift while placing it.

_I didn't test this on a clean server yet, so it could just be a plugin issue._

**Comment by me4502** [comment]
The text is case insensitive. It’s likely another plugin is causing these issues. CraftBook doesn’t check if the player is sneaking when creating the sign, it only cares about whether the sign has been made.

**Comment by krusic22** [comment]
Yeah, looked at the code and didn't find anything suspicious. 
Will look for suspect plugins and if I find anything I'll report back in case someone else has the same issue.
