### ISSUE TITLE
Missing Pipe Items for Brewing Stands

### ISSUE THREAD

**Issue by LordRazen** [EngineHub/CraftBook#1185]
The following items are piped to the brewing stand: 

- Pufferfish
- Phantom Membrane
- Dragon Breath
- Turtle Shell

Tested on the newest Craftbook Build / Spigot 1.15

https://minecraft.gamepedia.com/Brewing

**Comment by LordRazen** [comment]
Version: 3.10.2-SNAPSHOT;4573-d8a3e9d:

We recognized that water bottles arent transported to brewing stands via pipe, too (1.15.2)

**Comment by me4502** [comment]
Fixed
