### ISSUE TITLE
player_head not recognized properly as crafting input

### ISSUE THREAD

**Issue by Omanoctoa** [EngineHub/CraftBook#1192]
MC1.15.2
Using latest stable dev build (#4573)

When creating a custom crafting recipe, the minecraft:player_head is not recognized as an input item. All legacy variations (head:3, head_item:3, skull:3, skull_item:3) are translated into unrecognized items (stone) as crafting or furnace recipes. Using player_head as an output item works just fine (whether it has a skin specified or not), but as an input item it shows as unrecognized stone. Flattened zombie_head, creeper_head and wither_skeleton_skull input ingredients are unrecognized, as is any player_head with a defined skin, however work as intended as outputted results.

For instance this recipe, which should accept any variation of a player head regardless of skin as an input item, instance only accepts skeleton_skull items as an input, but outputs the generic player_head like it is supposed to...
`    cookedhead:
        type: Furnace
        ingredients:
            'minecraft:player_head ': 1
        cook-time: 500
        experience: 0.5
        results:
            'minecraft:player_head ': 1`

Using legacy item IDs such as the following, instead requires 3 unrecognized Stone as an input ingredient instead of a single player head item...

`    cookedskull:
        type: Furnace
        ingredients:
            'minecraft:skull:3 ': 1
        cook-time: 500
        experience: 0.5
        results:
            'minecraft:player_head ': 1`

PS- The server was restarted (shutdown, wait, Start) for all testing and recipes are not properly reloaded.

**Comment by me4502** [comment]
This was probably fixed by Spigot in 1.16 with their recipe fixes.

If that doesn't resolve it, it's still a spigot issue either way.
