### ISSUE TITLE
Problem with crafting recipes

### ISSUE THREAD

**Issue by tonyZxD** [EngineHub/CraftBook#1194]
I can't craft with new items like "Phantom Membrane"
In craft recipe they included, but when go craft, craft without that item.

I use last version of CraftBook

**Comment by me4502** [comment]
If you're sure that you're using the correct ID from the MC wiki, this is a bug in Spigot.

Many new or flattened items cannot be used in recipes in Spigot, due to bugs in their recipe system. There's nothing CraftBook can do to work around the issue.
