### ISSUE TITLE
Light switch bug

### ISSUE THREAD

**Issue by emkirsh** [EngineHub/CraftBook#1199]
**Versions**

CraftBook version: 3.10.2-SNAPSHOT;4573-d8a3e9d
Bukkit version: git-Paper-237

**Describe the bug**

The light switch doesn't revert the "off" (redstone) torches back to normal without having to switch the block.

**To Reproduce**

1. ... make a light switch and put a torch
2. ... toggle it
3. ... attempt to toggle it back

**Expected behavior**

The torches will change to redstone torches, and they will all be facing north, and they won't toggle back unless you replace the torch above the sign with a redstone torch. This also broke redstone contraptions nearby because it didn'tr remember which torches it originally changed, so it found redstone torches that were there all along and broke my rail system along with the secret door.

**Screenshots**

[Here is the Gyazo album.](https://gyazo.com/collections/f0258d511e808e4adb3808760d082c83)

**Additional context**

It's unclear as to whether or not replacing the torch above the sign is intentional, but I know that it should store memory so it doesn't break Redstone torches that were there originally. And of course, Spigot broke the direction thing again so I know the north thing is unintentional.

**Comment by me4502** [comment]
So I fixed the directions being odd, and also lowered the timeout time from 5 seconds to 1 second.

The mechanic does not know where nearby redstone mechanics are however, it has no way of determining what was meant for a redstone contraption and what wasn't
