### ISSUE TITLE
XPStorer bugs

### ISSUE THREAD

**Issue by MrEDok** [EngineHub/CraftBook#1200]
**Versions**
CraftBook version: 3.10.1;d29bd15
Bukkit version: Purpur version git-Purpur-579

**Describe the bug**

Creating [XP] sign throw error and block doesn't store dropped XP(s)
**To Reproduce**
1. Place block in config
----
    XPStorer:
        require-bottle: true
        xp-per-bottle: 16
        block: minecraft:slime_block
        require-sneaking-state: 'no'
        radius-mode: true
        radius: 5
----
2. place sign [XP] this will throw error [https://pastebin.com/CGK45GLW](https://pastebin.com/CGK45GLW)
3. drop xpbottle or kill mobs XP(s) wont get merge/collect b the block [https://streamable.com/lbpwty](https://streamable.com/lbpwtyl)

**Expected behavior**
xp-orbs get collect into the block

**Comment by me4502** [comment]
You have require-bottle set to true, which is why they aren't creating bottles when in radius mode. You need a chest above the slime block with empty bottles in it
