### ISSUE TITLE
Bugs with Water Bottles, Pipes and Brewing Stands

### ISSUE THREAD

**Issue by LordRazen** [EngineHub/CraftBook#1201]
**Versions**
Version: 3.10.2-SNAPSHOT;4610-fe198aa
git-Paper-213 (MC: 1.15.2)

**Describe the bug**
http://prntscr.com/skbwyv

With the upper testsetup, I tried to pipe waterbottles and fireresistance potions to the brewing stand
Two bugs happened:
- With one potion in the chest and one blick on the button, there were three water bottles in the brewing stand and the potion was still in the chest 
-> item dupe (1 -> 3)
-> nbt tags of potions are ignored (fire resistance -> water bottle)

**Comment by me4502** [comment]
I cannot reproduce this now - This was likely a bug with the BrewingStand inventory in older versions of Spigot.
