### ISSUE TITLE
Better Piston causing TPS lag

### ISSUE THREAD

**Issue by blek-id** [EngineHub/CraftBook#1202]
**Versions** 3.10.2-SNAPSHOT;4569
Bukkit version: 1.13.2

**Describe the bug**
When using higher pushdistance for superpush and supersticky, it will cause the TPS to go down instantly

**To Reproduce**

1. Create superpush piston
2. write 10-1000000 in line 3

**Expected behavior**
TPS doesn't go down. Or probably add an option to set max push distance?

**Comment by me4502** [comment]
There is a max distance. It's 12 by default
