### ISSUE TITLE
Hidden Switch any-side broken

### ISSUE THREAD

**Issue by kikelkik** [EngineHub/CraftBook#1205]
**Versions**
CraftBook version: CraftBook version 3.10.2-SNAPSHOT;4610-fe198aa
Bukkit version: git-Paper-318 (MC: 1.15.2)

**Describe the bug**
HiddenSwitch [X] can not be triggered by side blocks since 1.15.

**To Reproduce**
1. CraftBook/mechanisms.yml : HiddenSwitch.any-side: true
2. Create a Hidden Switch with [x] sign and lever.
3. Test correct behaviour by clicking the block where the sign is attached to.
4. Click on a block attached to a side of the [x] sign. => The lever will not trigger.

**Comment by me4502** [comment]
I cannot reproduce this issue, it's working fine for me?

**Comment by kikelkik** [comment]
Originally, the button has been triggered when clicking on each of the green blocks. Now, it's only the sign-block which works.

![2020-05-27_13 40 21](https://user-images.githubusercontent.com/14167723/83014845-b89dc880-a01f-11ea-8e5c-a9057f1fd5cc.png)

**Comment by me4502** [comment]
That's incorrect behaviour - Due to a Spigot bug I had to temporarily remove the check that prevented that from working, but the bug was later fixed so the check was able to be re-added.

**Comment by kikelkik** [comment]
OkayI did'nt know that. Thanks for your help!
