### ISSUE TITLE
MC2100 Delayer not switching anymore

### ISSUE THREAD

**Issue by BrianAlbersNL** [EngineHub/CraftBook#1206]
**Versions**

CraftBook version: 1.10.1
Bukkit version:  1.15.2

**Describe the bug**

When building an MC2100 it says "succesfully build Delayer", but nothing happens after the seconds. Lever at the other side of block does not switch.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hvm2308** [comment]
Never experienced a problem with the Delayer and just checked it on a 3.10.2-Snapshot -- it works. Most likely you're doing something wrong. I suggest you ask on Discord for help.

**Comment by me4502** [comment]
Please provide a screenshot of the setup, the delayer works fine

**Comment by me4502** [comment]
Cannot reproduce
