### ISSUE TITLE
comitems player_chat event not working

### ISSUE THREAD

**Issue by Goncorer** [EngineHub/CraftBook#1208]
**Versions**
CraftBook version: 3.10.1;d29bd15
Bukkit version: git-Spigot-a99063f-fad2494

**Describe the bug**
When activating a command item with the PLAYER_CHAT event, the item does not activate, and this error appears in the console:
[https://pastebin.com/udTVCP53](url)

**To Reproduce**
1. create a command item on the PLAYER_CHAT event running any command and try to use it

**Expected behavior**
Attempting to make a console microphone that sends any message you say while holding it as a console /say command.
Commands: say @m
run-as: CONSOLE
Instead the above error occurs

**Comment by me4502** [comment]
Fixed.
