### ISSUE TITLE
Inconsistent behaviour with Elevator Smooth-Movement

### ISSUE THREAD

**Issue by xRebellion** [EngineHub/CraftBook#1210]
**Versions**

CraftBook version: 3.10.2-SNAPSHOT;4573-d8a3e9d
Bukkit version: 1.15.2 (Paper Build 350)

**Describe the bug**

When enabling smooth movements, Lift Up immediately teleports the player up when there are blocks in the middle, but Lift Down does not, and end up making the player phase inside the wall, damaging the player.

**To Reproduce**

1. Make a 1x1 pillar with a noticeable height
2. Create elevator signs for the upper and lower part
3. Use the elevator. It has different behavior for teleporting up or down

**Expected behavior**

Upon clicking lift down, the player gets teleported to the highest teleportable block, then continuing smooth movement from there. Or just teleport down immediately, as long as it does not make the player phase through blocks.

**Screenshots**

Elevator Setup:
![image](https://user-images.githubusercontent.com/32483348/85754326-2af4ec00-b737-11ea-9910-0b756cbc99e3.png)

**Comment by me4502** [comment]
Smooth movement isn't really a supported feature anymore, as Spigot bugs have made it rather unusable - but I'll look into this if I get a chance

**Comment by me4502** [comment]
Closing this as smooth movement of the elevator is a discontinued feature. It's not possible to support this in a safe and stable way with Spigot anymore.
