### ISSUE TITLE
Bridge and Door mechanic broken and cause error on start

### ISSUE THREAD

**Issue by Tsoccerguy3** [EngineHub/CraftBook#1211]
**Versions**

CraftBook version: build 4619
Bukkit version: Paper 1.16.1 build 34

**Describe the bug**

Bridge and Door mechanics crash on start , I believe this is a old bug and a conflict with Player ID's and FAWE . Ive included a log

**To Reproduce**

1. ... include FastAsyncWorldEdit-1.16-273
2. ... start server

**Expected behavior**

expect Bridge and Door to work , does nothing

**Screenshots**

**Additional context**

[2020-07-01-3.log.gz](https://github.com/EngineHub/CraftBook/files/4859057/2020-07-01-3.log.gz)

**Comment by me4502** [comment]
If FAWE breaks CraftBook, it’s a FAWE issue and there’s nothing that can be done about it from my end.

CraftBook uses the WorldEdit API. If they break the WorldEdit API and tell other plugins that they are WorldEdit, their plugin is broken.
