### ISSUE TITLE
Cauldron not working! 1.16.1 SPIGOT

### ISSUE THREAD

**Issue by Nidrux** [EngineHub/CraftBook#1216]
**Versions**

CraftBook version: 3.10.2
Bukkit version: git-Spigot-0287a20-7560f5f (MC 1.16.1) API VERSION: 1.16.1-R0.1-SNAPSHOT

**Describe the bug**

The cauldron just doesn't work. No message no event.
**To Reproduce**

1. Setup cauldron (nether rack with fire -> Cauldron above the fire -> fill with water)
2. Throw in default items (template from wiki)  

**Expected behavior**

Some sort of effect and then a diamond block (from template)
**Screenshots**

none
**Additional context**

I've created my own cauldron-recipes.yml file and pasted in the template

**Comment by me4502** [comment]
If you right-click an empty cauldron, does it provide the message stating that you haven't provided any ingredients?

I cannot reproduce any issues, it is working entirely fine for me on 1.16.1 on my test server with only WorldEdit and CraftBook.
