### ISSUE TITLE
@b.t returns block type incompatable with minecraft's namespaced ID system

### ISSUE THREAD

**Issue by BeeFox-sys** [EngineHub/CraftBook#1222]
**Versions**

CraftBook version: 3.10.2
Bukkit version:  git-Spigot-379750e-82542d0 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Describe the bug**

When using command items, @b.t returns the spigot name, which due to being in all capitals is incompatible with minecraft commands.

**To Reproduce**

1. Create a command item with `say @b.t` as a command, and `CLICK_RIGHT_BLOCK` as the click type
2. use the command item, and see that the block name is in all capital letter
3. attempt use the setblock command with the block name supplied by @b.t (for example, `/setblock ~ ~ ~ COBBLESTONE`
4. observe that minecraft errors the command, stating it is not a block

**Expected behavior**

For @b.t to return a minecraft compatible block type, for example rather then `COBBLESTONE` it should return either `cobblestone` or `minecraft:cobblesone`

**Screenshots**

**Additional context**

**Comment by me4502** [comment]
Fixed by 6e1c665a9de3ef12354ec6366c38410b558e10c2

@b.t now returns `minecraft:cobblestone`, and @b returns COBBLESTONE
