### ISSUE TITLE
Error and warning ERROR Spigot error when saving item meta

### ISSUE THREAD

**Issue by Klawdek** [EngineHub/CraftBook#1224]
**Versions**

CraftBook version: 3.10-rc-2;4e5f9b1
Bukkit version: git-Paper-387 (MC: 1.15.2)

Craftbook and paper are the latest versions as of this post.  I even upgraded paper from a few versions behind and the error still occurs. 

**Describe the bug**

Here is the console log the error just occurs no one needs be on the server or do anything it just spontaneously occurs
https://pastebin.pl/view/8bdbfb2c
**To Reproduce**

1. ...  Install craftbook 
2. ...  Wait a little while and the error will occur.

**Expected behavior**

No errors
**Screenshots**

**Additional context**

**Comment by me4502** [comment]
That error is entirely Citizens, nothing to do with CraftBook.

Also you should be using an actual release of CraftBook for 1.15.2 rather than that build.
