### ISSUE TITLE
A Sorter-IC similar to the MC1229 that is able to distribute items based on percentages (specific percentage of items going to the left/right of the circuit)

### ISSUE THREAD

**Issue by w1tcherrr** [EngineHub/CraftBook#1227]
**Is your feature request related to a problem? Please describe.**
Let's say you have a tree farm that produces a specific amount of oak-logs an hour. With the automatic crafting IC it is possible to automate making all of the logs into planks. But if you only wanted 50% of your logs to be made into the planks and the rest put into storage you have a problem. You can't really reliably split all the incoming logs within a pipe so that 50% of them go to the automatic crafting table and the other 50% going to a storage.

**Describe the solution you'd like**
It would be amazing to have sorter like the MC1229 but instead of sorting items it sends a specific percentage of the items that enter the chest to the left and the rest to the other side. This could possibly look exactly like the MC1229. To make the MC1229 you need to put [MC1229] in the second line of the sign and you can put "invert" into the third. For this Circuit you could put the percentage of items you want to go to the right in the third line (you don't need the "invert"-option as you can just change your percentage from 30% to 70% or similar) 

**Describe alternatives you've considered**
I do not know of any compelling alternative that isn't unnecessarily complicated. I though about a piston moving glass away and back into a pipe so that it sometimes changes the path the items flow through, but that is in no way a reliable or remotely good solution.

**Comment by me4502** [comment]
Already exists, MC1242 (Distributer)
