### ISSUE TITLE
Toggle sign erasing itself is lever faces a specific direction relative to the sign

### ISSUE THREAD

**Issue by CrystalShard981** [EngineHub/CraftBook#1229]
[x] toggle sign can erase itself if orientation of lever is facing a specific direction relative to sign.
Instructions:
Make toggle sign
Place lever adjacent to sign as required, but pointing toward the sign.
Use block-switch
Observe sign

Video: 
https://www.youtube.com/watch?v=y8Y41VbGSCk

Paper: 1.16.3 Build 240
CraftBook: 3.10.3 Build 4656

PS: Should be using CraftBook 5 at this point?

**Comment by me4502** [comment]
Spigot bug but worked around in CraftBook
