### ISSUE TITLE
Add 1.16 Item Support to Cooking Pots

### ISSUE THREAD

**Issue by AetherisMC-Squid** [EngineHub/CraftBook#1230]
**Is your feature request related to a problem? Please describe.**

Cooking Pots do not support the new nether smeltables, despite 1.16 support by CraftBook.
Additionally, Cooking Pots do not smelt when heated by Soul Fire.

**Describe the solution you'd like**

Nether Gold Ore, Ancient Debris and Nether Bricks should be added as smeltables to cooking pots.
Cooking Pots should smelt when the fire underneath is Soul Fire (fire on Soul Sand / Soul Soil)

**Describe alternatives you've considered**

N/A

**Additional context**

1.16 support addition!

**Comment by me4502** [comment]
I've done this now, unsure what you mean by the nether bricks part though.
