### ISSUE TITLE
Snow Melt in Sunlight causes serverwide TPS plumet

### ISSUE THREAD

**Issue by junebug12851** [EngineHub/CraftBook#1231]
**Versions**

CraftBook version: 3.10.2
Bukkit version: 1.15.2 (Paper Build #389 [2020-10-11])
Java: OpenJDK 8
System: Debian 9

**Describe the bug**
Enabling the Snow mechanic with the option `melt-in-sunlight` being enabled results in a server-wide TPS plumet. This is true even with just one player in a non-snowy area.

**To Reproduce**
Set `melt-in-sunlight` to `true and enable the `Snowy` feature.

**Comment by me4502** [comment]
If you want to use the snow mechanic, use CraftBook 5. Spigot made some changes that made the old one not work correctly. Any mechanics that have been ported to CraftBook 5 are mostly only supported in CraftBook 5, snow moreso.
