### ISSUE TITLE
Realistic randoms sometimes causes server to hang at start

### ISSUE THREAD

**Issue by junebug12851** [EngineHub/CraftBook#1232]
**Versions**

CraftBook version: 3.10.2
Bukkit version: 1.15.2 (Paper Build #389 [2020-10-11])
Java: OpenJDK 8
System: Debian 9

**Describe the bug**
Enabling the option `realistic-randoms` sometimes causes the entire server to hang at start which, after 10 seconds, triggers the security system to try and restart the server since it would have been unresponsive for longer than 10 seconds. This seems to not always happen, I'm unsure what makes it happen. Disabling `realistic-randoms` fixes the problem.

**To Reproduce**
Set `realistic-randoms` to `true` in `config.yml`

**Comment by me4502** [comment]
Realistic randoms attempts to use Java's API a for secure hardware random numbers. Not all machines will support it properly. It sounds like yours doesn't, there's nothing that can be changed here as it's just a call to a Java API that would be hanging for you. I'd recommend you not use realistic randoms
