### ISSUE TITLE
Bridge Dupe Issue

### ISSUE THREAD

**Issue by g782Craft** [EngineHub/CraftBook#1234]
**Versions**
CraftBook version: 3.10.3 Build 4667
Paper build: 251

**Describe the bug**
You are able to dupe slabs with bridges. 

**To Reproduce**
1. Create bridge with slabs one whole block tall (2x slab)
2. Break a part of bridge to receive 2 slabs
3. Replace broken part with 1 slab instead of two
4. Toggle bridge
5. Observe 2-slab high block replacing single slab

**Expected behavior**
You shouldn't be able to turn 1 slab into 2 slabs.

**Comment by me4502** [comment]
This is scheduled for being fixed in CraftBook5. Due to the way it works at the moment, more fundamental changes need to occur and the WorldEdit API will be used in CraftBook5 to overcome these issues.

**Comment by me4502** [comment]
Fixed in https://github.com/EngineHub/CraftBook/commit/447c9f737dc1d2b4141fa6c3c3142d8ec074d844
