### ISSUE TITLE
Not working in 1.16.4 will not load throws exception error

### ISSUE THREAD

**Issue by Klawdek** [EngineHub/CraftBook#1239]
**Versions**

CraftBook version: craftbook-3.10.3-dist.jar
Bukkit version: git-Paper-335 (MC: 1.16.4)

**Describe the bug**

It will not load and gives the following exception: https://pastebin.com/aEeKdyqf
**To Reproduce**

1. Try to install on 1.16.4 server

**Expected behavior**

It load and not throw an exception

**Screenshots**

**Additional context**

**Comment by me4502** [comment]
You're missing worldedit

**Comment by Klawdek** [comment]
Sorry I thought that was installed.  It is on my list before craftbook but I somehow skipped it sorry for the trouble.
