### ISSUE TITLE
Craftbook Integrated Circuits and (in)direct redstone

### ISSUE THREAD

**Issue by Silacide** [EngineHub/CraftBook#1240]
After updating the server to paper 1.16.4 and craftbook to the latest stable version without changing anything else, I noticed that direct redstone doesn't trigger my IC signs anymore. I have indirect redstone enabled (which _does_ work) but isn't direct redstone supposed to always be enabled by default instead of only one of the 2? This kind of messed up a lot of my systems and since I didn't mess with anything in the config while updating I'm assuming this is a bug. No errors in console. Edit: if i extend the redstone line at the side of the lever it does activate the left one, but if it's directly connected to a lever it doesn't.

https://user-images.githubusercontent.com/67554908/103948048-6a19e600-5139-11eb-9a65-f8d36e18fec0.mp4

**Comment by me4502** [comment]
Spigot's redstone system has been getting progressively more broken each update. It doesn't inform plugins when that setup powers a sign. The supported behaviour is normal redstone wire going straight into the sign, not using a repeater etc.

**Comment by me4502** [comment]
For anyone who comes across this with the same issue, this is caused by the Paper eigencraft redstone option. It appears to prevent redstone events from occurring, therefore making plugins unaware that anything happened.
