### ISSUE TITLE
Add new mechanic 

### ISSUE THREAD

**Issue by danechek** [EngineHub/CraftBook#1245]
break individual slabs from double slabs just by aiming at them. By default it requires you to sneak to do this, which can be disabled in the config.

**Comment by me4502** [comment]
I don't understand what this is requesting sorry? What is this in relation to?

**Comment by danechek** [comment]
> I don't understand what this is requesting sorry? What is this in relation to?

https://www.spigotmc.org/resources/breakingslab-break-individual-slabs-while-sneaking.89632/
here, a useful improvement to the standard game mechanics, but installing a separate plugin for that...

**Comment by me4502** [comment]
This was decided to not be added, as it very much does not fit CraftBook at all
