### ISSUE TITLE
The Sign Copier doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [EngineHub/CraftBook#1248]
**Versions**
CraftBook version 3.10.4-SNAPSHOT;4695-9ae40fa
git-Paper-547 (MC: 1.16.5)

**Describe the bug**
The [Sign Copier](https://craftbook.enginehub.org/en/3.x/mechanics/sign_copier/) doesn't work under the [Paper Adventure System](https://github.com/PaperMC/Paper/pull/5289). Colour codes are not translated into colours, but are displayed in plain text on the sign.

**To Reproduce**
1. Copy a sign using an ink sac.
2. /sign edit 2 "&5&ltest"
3. Paste the edited text on the sign using an ink sac.

**Expected behavior**
The colour codes given shall be translated into the respective colour or formatting.

**Screenshots**
![sign](https://user-images.githubusercontent.com/24480321/111031480-0e552d00-8408-11eb-803c-331de52ce8da.png)

**Comment by me4502** [comment]
If Paper's adventure system has caused this, it's a Paper bug

**Comment by TheoRetisch1** [comment]
So it's not, like all the chat components stuff, a necessary adjustment to the new Adventure API system, but a bug. That's very good to know! Which method exactly is no longer working as it should? I can't open a paper bug report that says: The Craftbook Sign Copier doesn't work anymore, you must have destroyed the feature somehow with your new adventure stuff xD

**Comment by kashike** [comment]
![nope](https://i.imgur.com/h7Z15HH.png) Cannot confirm this to be working on a 1.16.4 build, which was pre-Adventure.

**Comment by TheoRetisch1** [comment]
I cannot confirm that. I just downgraded my test server to Paper 1.16.5 build 472 (a build before the Adventure System). And the sign copy function works for me. But very cool that you noticed the ticket! 
![sign copier](https://user-images.githubusercontent.com/24480321/111041561-05308400-8439-11eb-9ab3-b872f23cc911.PNG)

**Comment by kashike** [comment]
![nope](https://i.imgur.com/PEWoEXZ.png) cannot confirm on build 472 of Paper 1.16.5.

**Comment by TheoRetisch1** [comment]
I don't know what I'm doing different than you testing this. I reduced my plugins to a minimum and started using WorldEdit version 7.3.0-SNAPSHOT+5716-9a5ef70. The sign copier works on my testserver running Paper 1.16.5 build 472 and stops working with Paper 1.16.5 build 473. Using build 473 it doesn't even paste anything, but this is fixed in later Paper builds. Fact is it doesn't work for any of us in the latest paper version, whether this is due to Paper or not xD

**Comment by me4502** [comment]
This is intentional behaviour. A vast majority of users did not want colour conversions outside of the Minecraft section code translations.

Nothing is broken here.

**Comment by TheoRetisch1** [comment]
Uhm maybe I misused the feature in the last years. Please, can I or can I not edit colors on a sign using craftbooks sign copier?
