### ISSUE TITLE
Mechanic of sign edit

### ISSUE THREAD

**Issue by danechek** [EngineHub/CraftBook#1249]
https://craftbook.enginehub.org/en/3.x/mechanics/sign_copier/
it would be much better if the text editing mechanics worked a little differently - you click on the sign with ink and the editing window opens.  It is more convenient than chat command

**Comment by me4502** [comment]
That workflow doesn't overly make sense, as the sign copier mechanic at its base can be used to copy and paste sign text. Opening up the sign UI would make that more complex.

But also, in general, this is a significantly less flexible way of doing things, as commands allow for more flexibility than that UI.

Also, unless things have changed recently - this isn't possible without a few problems.

**Comment by danechek** [comment]
> That workflow doesn't overly make sense, as the sign copier mechanic at its base can be used to copy and paste sign text. Opening up the sign UI would make that more complex.
> 
> But also, in general, this is a significantly less flexible way of doing things, as commands allow for more flexibility than that UI.
> 
> Also, unless things have changed recently - this isn't possible without a few problems.

Okey, understood
