### ISSUE TITLE
area.use-permission issue/added feature?

### ISSUE THREAD

**Issue by idnthvn** [EngineHub/CraftBook#1252]
unsure if its craftbook or the plugin CHEST++  both awesome plugins. 
The issue i have is when you are doing PIPES and you pipe into a CHEST++ Chest, i get the area.use-permission error. It breaks the sign and doesnt allow you to use it. Now, i can place the sign on the piston, place a chest and do the CHEST++ chest and it allows it to function, HOWEVER, every item then gets voided/nulled out of the world. (kind of like a trash can) but does NOT sort any other along the rest of the pipeline. 
I am assuming this is intended to work as it should as the CHEST++ chest is a Player Protected Chest with its own security. 
Again, i do not know if this is a Craftbook or a CHEST++ thing, but this would be AWESOME to have as the CHEST++ acts as an Ender Chest that can be opened anywhere. PLUS you can open them with all blocks surrounding the chest, unlike vanilla where the chest needs 1 block above to be able to open. 

Please give this a consideration.
ALSO the TRASHCAN with pipes or even as an IC would be great. I seen this on another topic and i think that is a great idea (right now i use a dispenser with a clock and the redstone fire)
Thank you

**Comment by me4502** [comment]
That message means another plugin is telling CraftBook that the player isn't allowed to access the chest.

The second part where it's eating up items is definitely not CraftBook though, it only does a check if a chest already exists (if someone puts a chest next to an existing pipe it's their own fault, basically)

**Comment by idnthvn** [comment]
The first part. I understand what you mean. So Chest++ would have to give Craftbook an Okay to use the chest. Like a "fake player" I don't know if spigot has them or not. 
The second part. It's kind of mixed.   Bc Craftbook is attempting to put items in the chest, bc I hacked around the Craftbook check that you are explaining. But since the chest isn't allowing Craftbook to place items, then the items go away.   Again I see it's not Craftbook.    So I need to put this on chest++ page.   
Thank you though, I understand now :)

**Comment by me4502** [comment]
It's not CraftBook that needs the ability to open that chest, it's the player. CraftBook asks other plugins if that player is allowed to access the chest when the Pipe sign is made. If other plugins say no, CraftBook doesn't allow the action. You can disable CraftBook asking other plugins by disabling advanced-block-checks in the config.

As for the item stuff, yeah - CraftBook can't really control what Chest++ does, that very much sounds like an issue on their end if it breaks putting items in chests with the Spigot API.
