### ISSUE TITLE
Craftbook 5 Elevator Causes Server Crash

### ISSUE THREAD

**Issue by ArcticRaven** [EngineHub/CraftBook#1257]
**Versions**
CraftBook version: Craftbook-3.10.3 and CB 5.0.0 snapshot
Bukkit version: PurPur 1022

**Describe the bug**
When using Elevators from CB5 - If a [lift updown] does not find a elevator node above it - it will crash the server!

**To Reproduce**
1. Make a Lift UpDown sign
2. Attempt to go up

**Expected behavior**
If looping is enabled - attempt to place player at the next elevator in sequence, else message the player that there is no available elevator

**Screenshots**
N/A

**Additional context**
Added log of the stack trace that occurs when the sign is interacted with.
[2021-03-27-5.log](https://github.com/EngineHub/CraftBook/files/6215753/2021-03-27-5.log)

**Comment by me4502** [comment]
Fixed.
