### ISSUE TITLE
Could not pass event CartBlockImpactEvent when creating minecart station

### ISSUE THREAD

**Issue by Bloodlex** [EngineHub/CraftBook#1258]
**Versions**

This server is running Paper version git-Paper-550 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Describe the bug**
I cannot create a minecart station that allows me to launch minecart after providing redstone signal to station block (obisidian by default). There may be some other issues, I don't know exactly what this error below indicates.

Logs:
[https://pastebin.com/UjgSA8Ay](https://pastebin.com/UjgSA8Ay)

Mechanisms.yml
[https://pastebin.com/8ecXaNW3](https://pastebin.com/8ecXaNW3)

Config.yml
[https://pastebin.com/RZ9mRW6U](https://pastebin.com/RZ9mRW6U)

**To Reproduce**

1. Create a station block like in docs
2. Ride a minecart, stop at station try to run after clicking a button
3. Nothing happens

**Expected behavior**
Minecart should be launch according to the station sign direction.

**Additional context**
Plugins: AcoWorth*, ActionHealth*, AdvancedLogger*, AdvancedRegionMarket, ArmShopBridge, AsyncWorldEdit, AuthMe, BetterBees, BetterHeads, ChestSort, ColoredSigns*, CommandBlocks, CommandHelper, CommandNotifier, CommandPanels, ContainerPassthrough, CraftBook, DeathPenalties, Disease, dynmap*, Dynmap-WorldGuard*, EasyCarts, Essentials, EssentialsChat, GoldenEnchants, Harbor, HolographicDisplays, Images, InteractiveBooks, JetsAntiAFKPro, Jobs, KeepChunks, LangUtils, Lasso, LastLoginAPI, LeaderHeadsRevamped, LogBlock, LuckPerms, LWC, MinecartSpeedPlus*, MobArena, NBTAPI, NexEngine, NoElytra*, OpenInv, OreAnnouncer, Pingas*, PlaceholderAPI, Plan, PortalFix*, ProtocolLib, PvPManager, QuickShop, QuickShopDynmap, RegionRaid, SAML, SkinsRestorer, Spartan, SuperVanish, TitleManager, TradingCards, TreeAssist, Vault, VillagerOptimiser, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by me4502** [comment]
This is not the station, this is a cart booster that for some reason is being told that the cart's current velocity is infinite by Spigot.

Test with only CraftBook and WorldEdit, this is likely a bug in another plugin you're using (or Spigot)

**Comment by Bloodlex** [comment]
> This is not the station, this is a cart booster that for some reason is being told that the cart's current velocity is infinite by Spigot.
> 
> Test with only CraftBook and WorldEdit, this is likely a bug in another plugin you're using (or Spigot)

Hmm... I see, but stations don't work for me either 🙁

**Comment by me4502** [comment]
Join the Discord for support re: stations, they definitely work

**Comment by Bloodlex** [comment]
@me4502 Yes, you were right, stations work 👍 I must have done something wrong previously... I think the other exception can have something to do with EasyCarts or yet another plugin I have modifying the max speed of carts, this ticket can be closed now, thanks for the help! 🙂
