### ISSUE TITLE
Cooking pot 

### ISSUE THREAD

**Issue by danechek** [EngineHub/CraftBook#1259]
I suggest the replace required block (netherrack) to campfire block

**Comment by me4502** [comment]
As the campfire block is another tile entity, this would lead to the cooking pot mechanic requiring more tile entities. Plus, signs on campfires would not work as well as on a netherrack block.

From a performance perspective, this would be significantly worse than the current design

**Comment by danechek** [comment]
> As the campfire block is another tile entity, this would lead to the cooking pot mechanic requiring more tile entities. Plus, signs on campfires would not work as well as on a netherrack block.
> 
> From a performance perspective, this would be significantly worse than the current design

maybe then it would be possible to have a separate mechanism? for example, to open a fire like a chest, put raw food and coal there for cooking
