### ISSUE TITLE
Ic Problem with mc1111 and 1110

### ISSUE THREAD

**Issue by Blueeyestar** [EngineHub/CraftBook#1261]
Paperversion Paper version git-Paper-592 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Craftbook-Version: CraftBook_3.10.4-Build4700.jar

Good Morning,
we wanted to activate the transmitter and receiver IC's on our server.
We did that in the config
Then we created signs using

**Transmitter
[mc1110]
Channel123**

and

**Receiver
[mc1111]
Channel123**

it is also shown in the chat that it was created.

But the transmit no signal.

Are the ICs still active in Craftbook?

**Comment by CloudeLecaw** [comment]
I have the feeling that none if the ICs seems to work.
i tried some and none of them Seems to have an effect on Redstone

Are they really working?

**Comment by me4502** [comment]
The ICs work. What was likely the issue here is you didn't use the MC1111 in a self triggering mode, so it required a rising edge power signal.

Use [MC1111]S for self triggering
