### ISSUE TITLE
CB5 Mechanic bug: Better Ai causes mobs using 'attack passive' to not attack players

### ISSUE THREAD

**Issue by TheGam1ngWizard** [EngineHub/CraftBook#1263]
CraftBook version: CraftBook5 v5.0.0-SNAPSHOT;4704-2fd8bbb
Paper version: Paper version git-Paper-576 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

CB5 Mechanic bug: Better Ai causes mobs using 'attack passive' to not attack players
Replicatible by using the default config and spawning a zombie in survival mode
After removing the line (and leaving just a '-' so it doesn't regenerate) I reloaded the mechanic and zombies started pathing towards players again.

**Comment by me4502** [comment]
I've made a change that'll make it more reliable. Due to limitations in the Paper API, there's no way to guarantee this to ever be the case. However, it should *generally* be okay now.
