### ISSUE TITLE
SignEditor does not support color codes anymore.

### ISSUE THREAD

**Issue by mibby** [EngineHub/CraftBook#1264]
**Versions**

CraftBook version: 3.10.4-SNAPSHOT;4700-609e3e4
EssentialsX version: 2.19.0-dev+111-4976484
Bukkit version: git-Paper-643 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Describe the bug**
You can no longer use SignEditor to specify colors on a sign.

**To Reproduce**

1. Place down sign.
2. Grab ink sac.
3. Right click sign with ink sac.
4. Write "/sign edit 1 &btest"
5. Smack sign.

**Expected behavior**
The word test to be colored.

**Screenshots**
![link](https://i.imgur.com/YS789Xj.png)

**Additional context**
This use to work to cheese extra character space on a sign since formatting codes took up space. 

In EssentialsX config, enable the color sign option.
```
enabledSigns:
  - color
  ```

**Comment by me4502** [comment]
Ampersands have never been supported. It's always required using section signs for compatibility reasons.

**Comment by mibby** [comment]
Very weird, it use to work fine though. However alright, thanks.

**Comment by me4502** [comment]
If it was happening for you - another plugin was forcibly setting it

CraftBook has never done that as it severely limits what can be entered on the sign
