### ISSUE TITLE
CustomCraft Console Error Spam

### ISSUE THREAD

**Issue by aparry91** [EngineHub/CraftBook#1265]
**Versions**
CraftBook version:  v3.10.4-SNAPSHOT
Bukkit version: Paper-1.16.5
Chests++: v2.4.1

**Describe the bug**
I have setup a Custom Craft recipe, I have then linked it to work with the Chest ++ plugin to auto craft the custom recipe
it crafts the item as expected but I'm getting the following error each time the item is crafted

Console spam for CustomCraft items: https://pastebin.com/v8YUgL6h

**To Reproduce**

1. Custom Craft recipe setup
2. Item recipe setup on the Chest++ Autocrafter
3. Item is created
4. Check console out put and see error everytime item is created

**Expected behavior**
- [x] Custom Craft recipe setup
- [x] Item is setup in Chest++ Autocrafter
- [x] Item is created
- [ ] No console output

**Comment by me4502** [comment]
That looks to not be a CraftBook issue - for some reason your crafting inventory in the crafting event isn't a crafting inventory despite that being definitely the case.

It's like one of the other crafting related plugins you're using not correctly using the inventory interfaces
