### ISSUE TITLE
Server crashed because of to mich spam of this meassge

### ISSUE THREAD

**Issue by CloudeLecaw** [EngineHub/CraftBook#1267]
https://paste.gg/p/anonymous/9dafdf82438344a7a44aee2247421c97

This happens on server startup

- Paper 1.16.5 - Build 686
- CraftBook_3.10.4-Build4700

Result is the Server stops and refused to start - we tried to start it 5 times before we went back to PaperMC 670

Like you can see
from papersite they said its a problem we have to report to you

https://github.com/PaperMC/Paper/issues/5659

**Comment by me4502** [comment]
This does not look like an issue with CraftBook. It's just setting the sign back to the world as-is using the string compatibility layer, not specifically doing anything with it. It's likely either something else has created invalid signs, or it's a bug in Paper.

**Comment by CloudeLecaw** [comment]
i attached this issue on the papersite - may u can take a word there too

**Comment by me4502** [comment]
The main issue here is that the signs are being validated when they are read by plugins. So, therefore, this creates error spam that blames whatever plugin is the first to load the broken sign even if that plugin did not create the broken sign. 

There's nothing plugin developers can do about this. IMO the ideal solution would be for this warning to only be produced when a sign is set with invalid data, not read. As plugins can't tell if a sign would cause an error until after reading it, only Paper can do anything about this.

**Comment by CloudeLecaw** [comment]
unbeliveable they simply closed the issue and blocked further postings..

hm so what we can do here now?
Replace all sings on our servers and hope it does not come aggain? @,@

**Comment by SirYwell** [comment]
Update Paper, the check was disabled.

**Comment by CloudeLecaw** [comment]
Your right 691 fixed it.
