### ISSUE TITLE
Gatte, Bridge;xpstorer not work

### ISSUE THREAD

**Issue by eyebrawl123** [EngineHub/CraftBook#1268]
**5.0**

CraftBook version:5.0
Bukkit version:
This server is running Paper version git-Paper-684 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 4 version(s) behind
Previous version: git-Paper-675 (MC: 1.16.5)

unfortunately some things no longer work after an update to craftbook 5.0. (Bridge, gate, xpstorer)
I tried the following: / cb mech list ... none of the functions are displayed there

/ cb mech enable gate (not a valid mechanic type: gate

Can someone explain to me step by step how I can get these mechanics working again?

**Comment by me4502** [comment]
This is not a bug, these mechanics have not been ported over to CraftBook 5 yet.

See the pins in the Discord for more information.

**Comment by eyebrawl123** [comment]
Thanks for the quick answer. Unfortunately I cannot find any further information on CB5.0. are you planning to implement these functions again? If so, roughly when?

**Comment by me4502** [comment]
The information is available in the pins of the CraftBook channel of the Discord.

As for when - most of these features depend on changes to both WorldEdit and Paper, so I cannot give ETAs.
