### ISSUE TITLE
Minecart can be dismantled after restart

### ISSUE THREAD

**Issue by Blueeyestar** [EngineHub/CraftBook#1269]
Paper-Version: Paper version git-Paper-691 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

CraftBook_3.10.4-Build4700.jar

We have set up with Craftbook so that the users get a Minecart when they click on a rail and it is automatically removed when they get up.
That works very well in the game.

Now the problem:
You click on the rail and you sit in a minecart.
If you log out and log in again you can dismantle the minecart and it is yours. It will then no longer be drawn in by the plugin

**Comment by me4502** [comment]
This sounds like something else causing the issue. The carts are in no way tied to a player's login status, no data is stored on the player, only the minecart.

Either way - this mechanic has been ported to CraftBook 5 and is no longer supported on CraftBook 3.
