### ISSUE TITLE
MinecartDeposit Mechanic not collecting/depositing items.

### ISSUE THREAD

**Issue by CodeByCam** [EngineHub/CraftBook#1285]
**Versions**
CraftBook version: `3.10.6-SNAPSHOT;4740-a4101ed`
Bukkit version: `Paper-66 (MC: 1.18)`

**Describe the bug**
The minecart will not collect items from a deposit chest. Default configuration was used, with only the MinecartDeposit Mechanic enabled.

**To Reproduce**

1. Build yourself a small sorting system. 
2. Fill the deposit chest (tested with & without item names on the third line).
3. Power the minecart. 

**Additional context**
Also attempted to use the `collect.deposit.schem` provided in EngineHub's [Discord](https://discord.com/channels/80853743897149440/196180911098822656/761945353712173097). Original discussion on Discord can be found [here](https://discord.com/channels/80853743897149440/196180911098822656/916991519259492392).

**Screenshots**
![ZiAA9UA](https://user-images.githubusercontent.com/41496198/145871561-aef85b61-cec9-498b-bd45-5b4ed96170d6.png)

**Comment by me4502** [comment]
Cannot reproduce this issue. Was likely an early Spigot/Paper 1.18 bug.
