### ISSUE TITLE
Custom Drops Permissions not working

### ISSUE THREAD

**Issue by Caleston** [EngineHub/CraftBook#1287]
**Versions**
CraftBook version: 3.10.5
Bukkit version: git-Paper-388 (MC: 1.17.1), also git-Paper-402 (MC: 1.17.1)

**Describe the bug**
Require Permissions for Custom Drops has no effect in config. Also adding permission-node: to custom drops has no effect. 
Seems that even if they require permission, they still drop no matter what. Even a negative permission doesnt stop it. I was not OP'd. Using LuckPerms for permissions.

**To Reproduce**
1. Set a custom drop
2. Turn require permissions on in config for Custom Drops
 - 2.2 Optional: Set custom drop to require a permission node
3. Item still drops.

**Expected behavior**
Item does not drop unless user has the permission node required.

**Additional context**
Setting the permission to negative had no effect, still dropped. I was not OP'd.

**Comment by me4502** [comment]
This does work, something is wrong with your permissions setup if it isn’t.

use the discord for support.
