### ISSUE TITLE
Change default sign copier item

### ISSUE THREAD

**Issue by Phoenix616** [EngineHub/CraftBook#1288]
**Is your feature request related to a problem? Please describe.**

Currently (in both v3 and v5) the [default item for the sign copier](https://github.com/EngineHub/CraftBook/blob/master/src/main/resources/defaults/mechanisms.yml#L365) is the Ink Sac which historically didn't have any functionality. 1.17 added the functionality to make signs glowing with Glowing Ink Sacs though which also introduced the ability to "unglow" a sign with a normal Ink Sac. The sign copier using the same click event breaks that functionality.

**Describe the solution you'd like**

Ideally choosing a different default item (seeing as v5 is a complete rewrite this could be accepted by players better), I personally adjusted it in the config to Flint.

**Describe alternatives you've considered**

Manually adjusting the config if the unglowing is necessary or taking away the permissions.

**Additional context**

**Comment by me4502** [comment]
Fixed in 6b3910b4b86b7ba7b8f5dedfcb2c1c600b7d5372
