### ISSUE TITLE
Elevators not working with y levels below 0

### ISSUE THREAD

**Issue by Gungadean** [EngineHub/CraftBook#1290]
**Versions**
CraftBook version: 3.10.5
Bukkit version: git-Paper-71 (MC: 1.18.1)

**Describe the bug**
When using elevator signs which are located on opposing sides of y=0, elevator either cannot find the floor (using a lift to go down below y=0) or cannot find a destination (using a lift to go up above y=0). If both signs are located below or above y=0, the elevator works as intended.

**To Reproduce**
1. Place "[Lift Down]" above y=0.
2. Place "[Lift Up]" below y=0.

**Expected behavior**
Should work as a regular elevator and teleport you to intended destination elevator.

**Comment by me4502** [comment]
Already resolved weeks ago
