### ISSUE TITLE
BetterLeads takes too much leash 

### ISSUE THREAD

**Issue by CraftersX** [EngineHub/CraftBook#1293]
**Versions**

CraftBook version: craftbook-3.10.6
Bukkit version: Paper-42 (MC: 1.18)

**Describe the bug**
If we have several lanyards and we click it repeatedly on a mob set in the betterleads module, we lose the other lanyards and only one is left. 

**To Reproduce**
1. You must have at least 2 lanyards in your inventory in one hand 
2. Click on the mob in BetterLeads 
3. Keep clicking until the leash pops out into the ground
4. You now have one leash instead of two, where's the other? ;d

**Expected behavior**

Thrown out  all the leashes on the ground

**Video**
[[](https://youtu.be/S0tOvUhfyn8)](https://youtu.be/S0tOvUhfyn8)

**Additional context**

**Comment by me4502** [comment]
I cannot reproduce this; this was most likely a bug in the early versions of Paper 1.18 (or 1.18 itself)

Even trying with an entire stack, after picking them up I still have a full stack.
