### ISSUE TITLE
Auto-Craft IC(MC1219) LOSE items when face to a FULL Shulker Box

### ISSUE THREAD

**Issue by kites262** [EngineHub/CraftBook#1295]
**Versions**
CraftBook version: craftbook-3.10.6
Bukkit version: paper-1.18.1-178
**Describe the bug**

When a dropper face with a shulker box which is already full, the IC: Auto Craft could craft but missing the result of crafting.

**To Reproduce**

1.  A block with "[MC1219]S" sign is under a dropper.
2. The dropper is face to a already FULL shulker box
3. Then, the craft results could miss.

**Expected behavior**
1. The IC stops crafting.

**Screenshots**

**Additional context**

**Comment by me4502** [comment]
If this is happening, it's a spigot bug. CraftBook is just triggering the dispenser, anything beyond that point is handled by spigot.
