### ISSUE TITLE
Gate and Bridge issue

### ISSUE THREAD

**Issue by KamilKeK** [EngineHub/CraftBook#1296]
Hi, I'm trying to create Gate/Bridge as in _Doc 3.1/4.0_ described but when i use the sign I get "_Invalid material_" on Bridge not matter if it is in config or not (even with enforce-type: true/false) and in case of Gates it only fill 1st raw of fences no matter if its a 3x5 or 10x16 gate.

I have admin rank with "*", "worldedit.*", "worldguard.*", "craftbook.*", "craftbook.bridge/.use", "craftbook.gate/.use" and OP.

**Plugin versions:** _CB 3.10.7-SNAPSHOT_, _WE bukkit-7.2.10-SNAPSHOT_, _WG bukkit-7.0.6_.
_(I used released version of CB but it worked the same so i tried snapshot instead, didn't worked.)_

I'll try older versions of WE and see if it works in my free time.

**Comment by me4502** [comment]
This works fine using versions as described. Something in your setup is incorrect. Use the discord for support
