### ISSUE TITLE
Latest ProtocolLib breaks chairs and Craftbook.

### ISSUE THREAD

**Issue by crumpkatrina** [EngineHub/CraftBook#1297]
### CraftBook Version

3.10.6 Build 4739

### Platform Version

Paper 1.17.1 Build 409

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Latest commits:
https://github.com/dmulloy2/ProtocolLib/commit/073bfa2b86048aade0a0f32638f0255fdbd3f282
https://github.com/dmulloy2/ProtocolLib/commit/0d4e4c818f6263b1984da6c86880b26fd2750b26
https://github.com/dmulloy2/ProtocolLib/commit/d361526371262fe28155948d0ec7eae70a852470

Have broken CraftBook.
It will not load, states Chairs requires ProtocolLib, and instead shoots the following errors continously:
https://pastebin.com/raw/ZAsynKKh

Rolling back to:
https://github.com/dmulloy2/ProtocolLib/commit/f0059f39f60ba3fc62097700f0eaf0ea4e918142

Fixes all issues.

### Expected Behavior

Craftbook to function.

### Reproduction Steps

1. Use latest ProtocolLib dev builds with above CraftBook version.

**Comment by me4502** [comment]
You're missing the initial part of the error that actually shows what went wrong

It doesn't seem there was any intention for ProtocolLib to have breaking changes in those 3 commits, so it's most likely this is a bug in ProtocolLib - from the looks of it you're using dev builds of it, so it's likely due to that

**Comment by crumpkatrina** [comment]
Yes, I am using development builds of Protocollib.
There is nothing else earlier regarding errors, this is all that is shown.

**Comment by me4502** [comment]
It seems ProtocolLib dev builds are currently working towards a new major release. For us to support those would mean we'd lose support for the released versions. Don't use ProtocolLib 5 if you're wanting plugins that use ProtocolLib 4 to work. Once ProtocolLib 5 is the released version we can update to that, but breaking the plugin for everyone using the releases is not something we can do.
