### ISSUE TITLE
Silent Hidden Switch

### ISSUE THREAD

**Issue by ChrissW-R1** [EngineHub/CraftBook#1298]
### The Problem

If I click on a block with a hidden switch I will get a message in the chat, which tells me, that I've heard the switch. So the user knows, that there IS a hidden switch.

### A Solution

A property in the configuration, which disables the message of a hidden switch. So a hidden switch is really hidden.

**Comment by me4502** [comment]
You can just set it to blank in the language file if you want to remove it

**Comment by ChrissW-R1** [comment]
Nice idea, but don't work!
Now I see no text, but an empty chat line. So there is still an indicator about hidden switches.

My scenario is the following:
I want to create hidden switches for some puzzle maps. So, if an user test every block to check, if there is a hidden switch, there should be no audible or visual feedback, instead of all things, which will be triggered by the redstone signal.
