### ISSUE TITLE
Doors / Gates having issues

### ISSUE THREAD

**Issue by Kainzo** [EngineHub/CraftBook#1302]
### CraftBook Version

v3.10.7-SNAPSHOT;4754-8d6b614

### Platform Version

git-Paper-237 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: b55ba19)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Unable to use doors / gates, etc.

https://pastebin.com/iYTQcp07

### Expected Behavior

The doors/gates should function.

### Reproduction Steps

1. ...Have the versions required
2. ...Load the server

**Comment by me4502** [comment]
Don't lie when checking the boxes when making the ticket.

That error is inside FAWE, not CraftBook, and is caused by FAWE.
