### ISSUE TITLE
Sponge Behavior

### ISSUE THREAD

**Issue by crumpkatrina** [EngineHub/CraftBook#1303]
### CraftBook Version

3.10.7 Build 4754

### Platform Version

Paper 1.18.2 Build 335

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

We are using following config:

    Sponge:
        radius: 5
        circular-radius: false
        require-redstone: false
        include-wet: true

It seems that the sponges are not removing kelp/tall grass.
Meanwhile, in vanilla sponges do in fact remove those.
Can we please get CraftBook sponges to follow vanilla behaviour.

PS: This was not an issue when the sponge mechanism was in WorldEdit.

### Expected Behavior

Sponge and other plants to break correctly.

### Reproduction Steps

1. Use above config on water that have kelp/other plants.
2. Observe they do not break.
3. You are instead left with: https://i.imgur.com/rC4d55s.png

**Comment by me4502** [comment]
This was done intentionally to prevent them from being destructive to existing blocks

I suppose a configuration option could be added for it.

Also - Sponges were never in WorldEdit, the CraftBook Sponge mechanic isn't from anywhere and was made for CraftBook

**Comment by me4502** [comment]
So this is currently the behaviour of CraftBook sponges, however I've now added a configuration option to allow it to be disabled when not wanted.

**Comment by crumpkatrina** [comment]
Can you please add this to 3.10.7?
https://builds.enginehub.org/job/craftbook?branch=master
We are not yet using version 5.

**Comment by crumpkatrina** [comment]
@me4502
Can you please add this to 3.10.7?
https://builds.enginehub.org/job/craftbook?branch=master
We are not yet using version 5.
