### ISSUE TITLE
Add Sponge Improvements to master / 3.x

### ISSUE THREAD

**Issue by crumpkatrina** [EngineHub/CraftBook#1304]
### The Problem

 Feature request was added to 5.x, as opposed to master / 3.x which everyone uses: https://github.com/EngineHub/CraftBook/commit/eef222e9af97b24e7175a1c924f1829b9326b27e

### A Solution

Add to master / 3.x

**Comment by crumpkatrina** [comment]
@me4502 any news on whether you will push this improvement to 3.x which everyone uses. It’s been a few months, would love an update.

**Comment by me4502** [comment]
Feature development on 3.x features was stopped a while ago. I didn't add it to 5.x, it was already there - I just added an option to disable it.

If you want that, use the version in CraftBook 5 instead
