### ISSUE TITLE
Add Translation line for modul BoatWaterPlaceOnly

### ISSUE THREAD

**Issue by CloudeLecaw** [EngineHub/CraftBook#1306]
### The Problem

Currently the line when your using the modul BoatWaterPlaceOnly and try to place a boat on land is hardcoded and cant be changed.

### A Solution

Add a line for translation for modul (mechanic?) BoatWaterPlaceOnly

### Alternatives

Not really an alternative because it would not make sense to use an other plugin, when craftbook allready got this nice modul.

### Anything Else?

Tested in CraftBook_3.10.8-Build4762

**Comment by me4502** [comment]
This mechanic has been removed due to not working very well with Spigot, as well as not fitting very well into CraftBook (makes more sense for a protection plugin)

**Comment by CloudeLecaw** [comment]
what a luck its still part of current main version Craftbook 3x
