### ISSUE TITLE
CommandItems will not disappear when consume-self: true

### ISSUE THREAD

**Issue by malachy09** [EngineHub/CraftBook#1307]
### CraftBook Version

Latest

### Platform Version

Paper 1.19.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I have a CommandItem and I have it set to consume-self: true, I've reloaded the server and even reloaded the config files after every save and it still won't work. everytime I right click, the command itself works but the item does not disappear from the player's inventory. Any advice?

### Expected Behavior

It should make the item disappear on right click.

### Reproduction Steps

1. Item is right clicked.
2. Command works.
3. Item doesn't disappear on use.

**Comment by me4502** [comment]
Make sure you don't have the bypass consumables permission
