### ISSUE TITLE
invisible item frames

### ISSUE THREAD

**Issue by zymex22** [EngineHub/CraftBook#1310]
### The Problem

many servers have plugins like shops and other having hard time actually using {} and "" in auto commands and signs/shops
so selling or giving players invisible item frames is not possible.

### A Solution

A way to make itemframes invisible, either by looking at them and write a command /toggle itemframes or something.
or a command for swap your itemframe stack into invis ones.

other solutions might be good too, just some way to make them invis =)
i know there are plenty small standalone plugins doing just this, but many servers are not willing to add single plugins as each mc update make server update more difficult to wait for alle plugins to update and test.

### Alternatives

a good way for admins to auto parse commands including "" or {}
thats needed in many special commands:
`/give @s minecraft:item_frame{EntityTag:{Invisible:1b}}`

### Anything Else?

this would be a Huge QoL update to many servers, and having a option to do so in such a big mod as craftbook, might be a great option to spread this option to players on server, for extra creativity.

**Comment by me4502** [comment]
I don't entirely understand this feature request - it sounds extremely out of scope for CraftBook. CraftBook adds new gameplay mechanics, not niche admin commands.

> a good way for admins to auto parse commands including

I don't know what you mean by this, but all mechanics that make sense to include the ability to send commands can send commands. Eg, CommandItems, CustomCrafting, CommandSigns, etc

Given CraftBook is not a general commands plugin and instead a gameplay mechanic plugin (none of which operate by commands, but some contain commands for further functionality), I'm closing this feature request. This sounds more like something you should request to EssentialsX, which is actually a commands plugin

**Comment by zymex22** [comment]
@me4502 
sorry crappy explanation =)
it was not as a command but rather like this one:
https://www.spigotmc.org/resources/invisibleitemframes-better-item-frames.85085/

it would be something similar to painting changer, jacko lantern redstone and other QoL features already included in craftbook =)
