### ISSUE TITLE
Aliases for Pipes

### ISSUE THREAD

**Issue by Holocus** [EngineHub/CraftBook#1311]
### The Problem

I'm really fond of the Pipe function but it's getting increasingly difficult to make neat due to the limited size of filters being able to fit on a signpost.
It would be absolutely amazing if it was possible to make a simple list file in the plugin folder with aliases for items.
For example
Alias.txt
[Woodslabs]
126,126:1,126:2,126:3,126:4,126,5,minecraft:petrified_oak_slab
[Saplings]
6,6:1,6:2,6:3,6:4,6:5

etc etc
and then on the pipesign just use:
[Pipe]
#Woodslabs
to filter all the items listed under [Woodslabs] in the file.
 with this we could streamline the piping and make it neater and compact!

### A Solution

Have the option to make a text file in the pluginfolder and add our own list of aliases for the pipe function to also look for when doing it's filtering logic on the content for example:
Alias.txt
[Woodslabs]
126,126:1,126:2,126:3,126:4,126,5,minecraft:petrified_oak_slab
[Saplings]
6,6:1,6:2,6:3,6:4,6:5

### Alternatives

Right now it's limited to how much text can be fitted onto a sign how many items could be filtered into a chest. with a doublechest and two pistons it can fit double the amount, but with the newer items not having ID's but long names like minecraft_petrified_oak_slab won't even be able to fit a signpost at all.

**Comment by me4502** [comment]
You can already use variables to create aliases for anything anywhere

**Comment by Holocus** [comment]
> 

I'm sorry what? and if so, how would I do that for the purpose I'm looking for?

**Comment by me4502** [comment]
It's covered on the docs. Use the discord for support
