### ISSUE TITLE
MC1239 Harvester - doesn't collect bamboo

### ISSUE THREAD

**Issue by PowerSlime** [EngineHub/CraftBook#1314]
### CraftBook Version

3.10.8

### Platform Version

git-Purpur-1979

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

While placing harvester block it doesn't collect bamboo even when radius is specified, nether region.

### Expected Behavior

It should collect bamboo block as sugar cane ones

### Reproduction Steps

1. Put a block
2. Above it a chest
3. Put a sign on the block put in step 1 with next lines:
3.1. Empty
3.2. [MC1239]S
3.3. 5
4. Confirm it

See attached screenshot.

### Anything Else?

Minecraft 1.19.4

![2023-06-20_12 57 30](https://github.com/EngineHub/CraftBook/assets/18900377/abcd8462-ee98-4c03-a7c3-081db08cd6ff)

**Comment by me4502** [comment]
I don't have a chance to check right now, but this might be related to the fact that Spigot for some reason does not consider bamboo a type of tree despite MC code considering it that
