### ISSUE TITLE
Hidden Switch Permissions

### ISSUE THREAD

**Issue by crumpkatrina** [EngineHub/CraftBook#1317]
### CraftBook Version

5.0.0 Craftbook

### Platform Version

Paper 1.20.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I notice the craftbook 5 wiki mentions Hidden-Switches (https://craftbook.enginehub.org/en/5.0.0/mechanics/hidden_switch/) but I cannot seem to find where to activate them. Are these implemented in CB5?

### Expected Behavior

Be able to find and enable permissions for Hidden Switches

### Reproduction Steps

1. Attempt to find/enable Hidden Switch permissions
2. Unable to find permissions mentioned on documentation

**Comment by me4502** [comment]
This isn’t in CraftBook 5 yet, as covered by the CraftBook 5 information available - it depends on external changes that haven’t happened
