### ISSUE TITLE
Errors on reload with certain mechanics enabled

### ISSUE THREAD

**Issue by crumpkatrina** [EngineHub/CraftBook#1318]
### CraftBook Version

5.0.0 Craftbook

### Platform Version

Paper 1.20.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When _dispenser_recipes: true_ the above error occurs on /craftbook reload
https://pastebin.com/XU49H6BM

When _minecart_station: true_ the above error occurs on /craftbook reload
https://pastebin.com/SaLixcfW

### Expected Behavior

Craftbook reloads with all mechanics enabled

### Reproduction Steps

1. Have dispenser_recipes: true
2. Do /craftbook reload

1. minecart_station: true
2. Do /craftbook reload

**Comment by me4502** [comment]
CraftBook 5 requires WorldEdit 7.3

**Comment by crumpkatrina** [comment]
@me4502 is this still the case (requiring WorldEdit 7.3 for Craftbook 5)
It seems that WorldEdit 7.3 does not work with 1.20.2 however WorldEdit 7.2.17 does.
It also seems that CraftBook loaded fine on 7.2.17. Are we okay to use CraftBook 5 with WorldEdit 7.2.17, or should we wait for 1.20.2 to be added to WorldEdit 7.3 (?)
https://pastebin.com/raw/4GMyBY1p

**Comment by me4502** [comment]
Yes, it's still the case and 7.3 already supports 1.20.2
