### ISSUE TITLE
Tree Lopper respecting logging plugins

### ISSUE THREAD

**Issue by Zhincore** [EngineHub/CraftBook#1320]
### The Problem

The documentation for Tree Lopper says it respects logging plugins, so I expected that it won't cut down player-built logs, but that doesn't seem to be the case. I use CoreProtect as a logging plugin.

### A Solution

Tree Lopper should check with CoreProtect whether the block it's about to break was built by a player. This would require tree growing logging to be disabled in CoreProtect, but I think that is a small sacrifice.

**Comment by me4502** [comment]
What that means is, that CraftBook provides information to other plugins and abides by what they tell it to do.

So it'll let plugins log, and if those plugins tell it the player isn't allowed to break the blocks it'll respect it.

What you're requesting isn't CraftBook respecting but CraftBook adding additional functionality, and infeasible for numerous reasons

**Comment by Zhincore** [comment]
Aah, I see, alright then. Thank you for your response!
