### ISSUE TITLE
Lift arrivals broken on y levels -1, 0 and 1.

### ISSUE THREAD

**Issue by andrewkm** [EngineHub/CraftBook#1321]
### CraftBook Version

5.0.0-SNAPSHOT+4806-e519d28

### Platform Version

git-Paper-378 (MC: 1.20.4) (a58e29d)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Lift destinations placed on y-levels -1, 0, and 1, do not work. They work everywhere else. Lifts placed on these levels do work to travel out from, however arriving at these lifts does not work. 

### Expected Behavior

Arrival at these lifts to work as they should.

### Reproduction Steps

Make a proper [Lift] at Y level -1, 0 or 1, and attempt to arrive at it from another [Lift].

**Comment by me4502** [comment]
Fixed in https://github.com/EngineHub/CraftBook/commit/ad4b8cc5354817fb6634fec99664814b6b8a4c46
