### ISSUE TITLE
(BetterAI) Mobs with attack-passive enabled will attack ones attached to jockeys 

### ISSUE THREAD

**Issue by Aviside** [EngineHub/CraftBook#1326]
### The Problem

In BetterAI I have mobs attacking passive ones enabled. But I run into this problem where they will attack the passive animals on jockeys which results in them being disassembled. Mounts are quite helpful for hostile mobs and having them killed reduces their lethality.

Any feature that solves this would be greatly appreciated, thanks for your time! 

### A Solution

Developing a config option that checks if a passive entity is mounted to a hostile entity before the targeting is decided. 
(If the passive mob has a hostile rider, don't target it.)

**Comment by me4502** [comment]
Added in e78d0d3cc33a027473d0809c2c3ee507c517ff13
