### ISSUE TITLE
Lift taking damage

### ISSUE THREAD

**Issue by Dragsio** [EngineHub/CraftBook#1327]
### CraftBook Version

3.10.10-SNAPSHOT;4807-8aeb475

### Platform Version

git-Purpur-2162 (MC: 1.20.4)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Is there any way to fix or prevent taking damage while using the lift up/down?

### Expected Behavior

The player should not take damage when teleporting to the target floor.

### Reproduction Steps

1. On top block I write to second line of sign `[Lift down]`
2. On bottom block I write to second line of sign `[Lift up]`
3. When I reach the target destination, I take health damage and die.

### Anything Else?

![image](https://github.com/EngineHub/CraftBook/assets/48870248/dfbdd612-a669-43a6-8ebd-ebb734ba5f20)

**Comment by me4502** [comment]
This looks like it's a bug with something else, CraftBook just performs a basic teleport using the Bukkit API, which explicitly cannot cause this.

Try it with Paper instead of Purpur (as Purpur has been known to contain many bugs in the past that lead to weird behaviour like this), and with WorldEdit as the only other plugin.

**Comment by me4502** [comment]
closing this due to no response and not being able to reproduce the issue.
