### ISSUE TITLE
Duplicate placeholder in translation key

### ISSUE THREAD

**Issue by Tig3r98** [EngineHub/CraftBook#1329]
### CraftBook Version

5.0.0-beta

### Platform Version

Paper 1.20.4 493

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The translation key `craftbook.togglearea.deleted-area`, as provided on Crowdin, has the following value:
`The area "{0}" within the "{0}" namespace has been deleted.`
The placeholder '{0}' is duplicated, it's clearly not meant to be.

### Expected Behavior

The string should probably be:
`The area "{0}" within the "{1}" namespace has been deleted.`

### Reproduction Steps

None

**Comment by me4502** [comment]
Fixed in https://github.com/EngineHub/CraftBook/commit/7c0b5747413a23ac202c0572a034b95bb48340a7
