### ISSUE TITLE
1.21 Issues (Ammeter, Lightstone, Painting Switcher)

### ISSUE THREAD

**Issue by andrewkm** [EngineHub/CraftBook#1330]
### CraftBook Version

CraftBook5 v5.0.0-SNAPSHOT+4845-1e3372c

### Platform Version

Paper version 1.21-38-master@1f5db50

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Ammeter is broken - our defined tool (coal) doesn't display redstone power strength when used.
Lightstone is broken - our defined tool (glowstone_dust) doesn't display light level when used.

Both are working fine on 1.20.6

Painting switcher doesn't rotate through the 20 new 1.21 paintings but seeing we have no config settings I can find to define those I assume its up to Craftbook5 to update and add those paintings(?)

### Expected Behavior

To function.

### Reproduction Steps

N/A

### Anything Else?

If you need any other information please let me know.

**Comment by me4502** [comment]
I'll take a look at the two tools, but as for the painting switcher that just sounds like Bukkit hasn't added them to the Art enum yet. CraftBook just uses that, as Bukkit doesn't expose it via registry

**Comment by me4502** [comment]
I cannot reproduce any issues with Ammeter or Lightstone, they both work fine for me on 1.21 using the listed Paper build. What else is on your server / are there any console errors? it's likely something else is going on

**Comment by andrewkm** [comment]
Looks like the origin of the item is what is causing it to not work.
The items I was using in my original test were spawned in with /i or /give (minecraft:give). They have 7 components and don't work. https://i.imgur.com/tQuefJt.png

However if I use items naturally generated or via the Creative menu, they do work and have only 6 components: https://i.imgur.com/3W1u04r.png

**Comment by me4502** [comment]
CraftBook just compares the base item type using the Bukkit API method to do that. If different components on the item are somehow breaking item type comparisons, that sounds like a bug in Spigot or Paper

Although when I did testing I did it via the /give command

**Comment by andrewkm** [comment]
> CraftBook just compares the base item type using the Bukkit API method to do that. If different components on the item are somehow breaking item type comparisons, that sounds like a bug in Spigot or Paper
> 
> Although when I did testing I did it via the /give command

Alright, thanks, I'll investigate further and see if perhaps this is an issue with our item/give commands, specifically on our server.

**Comment by andrewkm** [comment]
Was an issue with our Essentials build.
![Code](https://i.imgur.com/BdNhQG7.png)
