### ISSUE TITLE
Unhandled exception occurred in onSyncPacket() for CraftBook5

### ISSUE THREAD

**Issue by andrewkm** [EngineHub/CraftBook#1337]
### CraftBook Version

CraftBook5 v5.0.0-SNAPSHOT+4868-4be5013

### Platform Version

Paper 1.21.3-44-master@85bfdc0

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using a version of CraftBook compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Getting spammed with the following simply by being on the server:
https://pastebin.com/raw/LhftYgHB

### Expected Behavior

Not get spammed.

### Reproduction Steps

Use above setup.

**Comment by me4502** [comment]
Fixed in https://github.com/EngineHub/CraftBook/commit/40f51b3d9842abca9d7698bb041c10d0b066a960 by removing ProtocolLib
