### ISSUE TITLE
Make XP-Bottle from XP-Storer renameable

### ISSUE THREAD

**Issue by Ceejuu** [EngineHub/CraftBook#1339]
### The Problem

If im using a custom amount of XP to store in a bottle via XP-Storer, players cannot indentify this bigger bottle from the vanilla ones.

### A Solution

Give us a config-string to be able to rename the generating XP bottle so we can set a new name to identify it.
Also, if possible, let us set another entity like the block from the XP-Storer so we can use custom items as bottle.

**Comment by me4502** [comment]
i'm not sure if just adding a name option is the best solution to this, i can see people requesting lore, etc too and massively overcomplicating this system.

might make sense to wait for an API that allows parsing item attributes from a string in Paper, and then merging that with the existing item stack

**Comment by me4502** [comment]
I've added this in https://github.com/EngineHub/CraftBook/commit/de5f44cb24875c5f9af10801866e2385fbd8e1c6

it basically just adds an option to define an itemstack using the MC syntax, and then it merges it with the item that the plugin makes. so the output item will be:

Your entry here + Data that makes it work.

**Comment by Ceejuu** [comment]
Thank you so much! I will check this :)
