### ISSUE TITLE
NPE - clickedPosition null on PlayerInteractEvent

### ISSUE THREAD

**Issue by andrewkm** [EngineHub/CraftBook#1340]
### CraftBook Version

CraftBook5 v5.0.0-SNAPSHOT+4879-d72d724

### Platform Version

Paper 1.21.4-34-main@d568e17

### Confirmations

- [x] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [x] I am using a version of CraftBook compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Errors in console:
https://pastebin.com/raw/uVCp2pBD

### Expected Behavior

No errors.

### Reproduction Steps

Unsure at this time.

**Comment by me4502** [comment]
does this always happen? i wonder if Paper broke the API while doing the hard fork refactors

**Comment by andrewkm** [comment]
Caught it a few times, seems to have started after hard fork.

**Comment by crumpkatrina** [comment]
@me4502 
Looks like we're getting this error every time any sign or hanging sign is left-clicked. It doesn't have to be an active Craftbook5 mechanic sign either. It happens with any placed sign.

**Comment by me4502** [comment]
this is something that must be fixed within Paper itself, the error is not happening within CraftBook code and therefore isn't happening in a spot that we can actually check if it's null or not

**Comment by andrewkm** [comment]
> [@me4502](https://github.com/me4502) Looks like we're getting this error every time any sign or hanging sign is left-clicked. It doesn't have to be an active Craftbook5 mechanic sign either. It happens with any placed sign.

Ah yeah, literally left clicking any sign causes this. xD

**Comment by me4502** [comment]
this is the Paper commit that introduced the bug, https://github.com/PaperMC/Paper/commit/083c083188825b6c758e700023541d4db7804502

you'd likely have to revert to a version prior to this until they've fixed it.

**Comment by me4502** [comment]
a fix for this is now in Paper. closing the issue now.

**Comment by andrewkm** [comment]
Confirmed fixed.
