### ISSUE TITLE
Pipes dont transport certain items to furnaces

### ISSUE THREAD

**Issue by LordRazen** [EngineHub/CraftBook#221]
- coral_blocks cannot be send to furnance burning slot with pipes
- dried_kelp_block and bamboo are not led to the fuel slot with pipes

**Comment by me4502** [comment]
What are coral meant to do in the burning slot? The MC wiki makes no mention of this on the smelting page - https://minecraft.gamepedia.com/Smelting#Recipes

**Comment by LordRazen** [comment]
uff... i forgot that this was a local change >.<

sorry, leaving the other two ...

**Comment by me4502** [comment]
In that case it’s already fixed

**Comment by ryantheleach** [comment]
If a datapack provides recipes, is there a way to check whether a furnace will accept an item that you could use?

**Comment by me4502** [comment]
Not with Spigot, the recipes API is currently not fully functional and hasn't been for a few years.
